-- ============================================================================
-- ATO Containment Service: DESIGN DRAFT of the database schema
--
-- NOT executed by the application yet. It documents the intended design and
-- will become JPA entities and/or migration scripts (e.g. Flyway) later.
-- You can try it manually:  mysql -u ato_user -p ato_db < database/schema_draft.sql
-- Requires MySQL 8.0+ (uses CHECK constraints, UUID(), JSON columns).
--
-- Note on IDs: MySQL has no native UUID primary-key default like PostgreSQL's
-- gen_random_uuid(). Ids are stored as CHAR(36) and are expected to be
-- generated by the application (or with DEFAULT (UUID()) on MySQL 8.0.13+,
-- shown below) before insert.
-- ============================================================================

-- ---------- Tenants ----------
CREATE TABLE tenants (
    id          CHAR(36) PRIMARY KEY DEFAULT (UUID()),
    name        VARCHAR(120) NOT NULL,
    slug        VARCHAR(60)  NOT NULL UNIQUE,
    status      VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE'
                CHECK (status IN ('ACTIVE', 'SUSPENDED')),
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tenant_security_settings (
    tenant_id                    CHAR(36) PRIMARY KEY,
    suspicious_threshold         INT NOT NULL DEFAULT 30 CHECK (suspicious_threshold BETWEEN 1 AND 100),
    high_risk_threshold          INT NOT NULL DEFAULT 70 CHECK (high_risk_threshold BETWEEN 1 AND 100),
    max_failed_logins            INT NOT NULL DEFAULT 5,
    failed_login_window_minutes  INT NOT NULL DEFAULT 10,
    recovery_token_ttl_minutes   INT NOT NULL DEFAULT 15,
    updated_at                   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CHECK (suspicious_threshold < high_risk_threshold),
    CONSTRAINT fk_settings_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id)
);

-- ---------- Users ----------
CREATE TABLE users (
    id                   CHAR(36) PRIMARY KEY DEFAULT (UUID()),
    tenant_id            CHAR(36) NOT NULL,
    email                VARCHAR(255) NOT NULL,          -- store lower-case
    password_hash        VARCHAR(100) NOT NULL,          -- BCrypt
    full_name            VARCHAR(120),
    role                 VARCHAR(20) NOT NULL DEFAULT 'USER'
                         CHECK (role IN ('USER', 'TENANT_ADMIN', 'SECURITY_ADMIN')),
    status               VARCHAR(30) NOT NULL DEFAULT 'ACTIVE'
                         CHECK (status IN ('ACTIVE', 'CONTAINED', 'RECOVERY_IN_PROGRESS', 'DISABLED')),
    failed_login_count   INT NOT NULL DEFAULT 0,
    last_login_at        TIMESTAMP NULL,
    password_changed_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_users_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id),
    CONSTRAINT uq_users_tenant_email UNIQUE (tenant_id, email),
    CONSTRAINT uq_users_tenant_id_id UNIQUE (tenant_id, id)   -- target for composite foreign keys
);

CREATE TABLE known_devices (
    id            CHAR(36) PRIMARY KEY DEFAULT (UUID()),
    tenant_id     CHAR(36) NOT NULL,
    user_id       CHAR(36) NOT NULL,
    device_hash   VARCHAR(64) NOT NULL,
    user_agent    VARCHAR(300),
    trusted       BOOLEAN NOT NULL DEFAULT FALSE,
    first_seen_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_seen_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_known_devices_user FOREIGN KEY (tenant_id, user_id) REFERENCES users (tenant_id, id),
    CONSTRAINT uq_known_devices UNIQUE (user_id, device_hash)
);

-- ---------- Sessions and tokens ----------
CREATE TABLE sessions (
    id              CHAR(36) PRIMARY KEY DEFAULT (UUID()),
    tenant_id       CHAR(36) NOT NULL,
    user_id         CHAR(36) NOT NULL,
    device_hash     VARCHAR(64),
    user_agent      VARCHAR(300),
    ip_address      VARCHAR(45),
    country         VARCHAR(2),
    status          VARCHAR(10) NOT NULL DEFAULT 'ACTIVE'
                    CHECK (status IN ('ACTIVE', 'REVOKED', 'EXPIRED')),
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_seen_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    expires_at      TIMESTAMP NOT NULL,
    revoked_at      TIMESTAMP NULL,
    revoked_reason  VARCHAR(30),                          -- LOGOUT, CONTAINMENT, TOKEN_REPLAY, ...
    CONSTRAINT fk_sessions_user FOREIGN KEY (tenant_id, user_id) REFERENCES users (tenant_id, id)
);

CREATE TABLE refresh_tokens (
    id               CHAR(36) PRIMARY KEY DEFAULT (UUID()),
    tenant_id        CHAR(36) NOT NULL,
    session_id       CHAR(36) NOT NULL,
    token_hash       VARCHAR(64) NOT NULL UNIQUE,         -- SHA-256 of the token, never the token itself
    parent_token_id  CHAR(36),                            -- previous token in the rotation chain
    used_at          TIMESTAMP NULL,                      -- set when rotated; reuse after this = replay
    expires_at       TIMESTAMP NOT NULL,
    created_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_refresh_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id),
    CONSTRAINT fk_refresh_session FOREIGN KEY (session_id) REFERENCES sessions (id),
    CONSTRAINT fk_refresh_parent FOREIGN KEY (parent_token_id) REFERENCES refresh_tokens (id)
);

-- ---------- Login history and risk ----------
CREATE TABLE login_events (
    id               CHAR(36) PRIMARY KEY DEFAULT (UUID()),
    tenant_id        CHAR(36) NOT NULL,
    user_id          CHAR(36),                            -- NULL when the email does not exist
    email_attempted  VARCHAR(255) NOT NULL,
    success          BOOLEAN NOT NULL,
    failure_reason   VARCHAR(50),
    ip_address       VARCHAR(45),
    country          VARCHAR(2),
    device_hash      VARCHAR(64),
    user_agent       VARCHAR(300),
    created_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_login_events_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id),
    CONSTRAINT fk_login_events_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE risk_assessments (
    id             CHAR(36) PRIMARY KEY DEFAULT (UUID()),
    tenant_id      CHAR(36) NOT NULL,
    user_id        CHAR(36) NOT NULL,
    login_event_id CHAR(36),
    session_id     CHAR(36),
    trigger_type   VARCHAR(20) NOT NULL
                   CHECK (trigger_type IN ('LOGIN', 'TOKEN_REFRESH', 'API_REQUEST')),
    score          INT NOT NULL CHECK (score BETWEEN 0 AND 100),
    risk_level     VARCHAR(12) NOT NULL
                   CHECK (risk_level IN ('NORMAL', 'SUSPICIOUS', 'HIGH_RISK')),
    signals        JSON NOT NULL,                          -- e.g. [{"name":"NEW_DEVICE","points":20}]
    decision       VARCHAR(20) NOT NULL
                   CHECK (decision IN ('ALLOW', 'STEP_UP', 'DENY_AND_CONTAIN')),
    created_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_risk_assessments_user FOREIGN KEY (tenant_id, user_id) REFERENCES users (tenant_id, id),
    CONSTRAINT fk_risk_assessments_login FOREIGN KEY (login_event_id) REFERENCES login_events (id),
    CONSTRAINT fk_risk_assessments_session FOREIGN KEY (session_id) REFERENCES sessions (id)
);

CREATE TABLE step_up_challenges (
    id                  CHAR(36) PRIMARY KEY DEFAULT (UUID()),
    tenant_id           CHAR(36) NOT NULL,
    user_id             CHAR(36) NOT NULL,
    risk_assessment_id  CHAR(36) NOT NULL,
    login_event_id      CHAR(36) NOT NULL,
    otp_hash            VARCHAR(64) NOT NULL,
    attempts            INT NOT NULL DEFAULT 0,
    status              VARCHAR(10) NOT NULL DEFAULT 'PENDING'
                        CHECK (status IN ('PENDING', 'PASSED', 'FAILED', 'EXPIRED')),
    expires_at          TIMESTAMP NOT NULL,
    created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_step_up_user FOREIGN KEY (tenant_id, user_id) REFERENCES users (tenant_id, id),
    CONSTRAINT fk_step_up_risk FOREIGN KEY (risk_assessment_id) REFERENCES risk_assessments (id),
    CONSTRAINT fk_step_up_login FOREIGN KEY (login_event_id) REFERENCES login_events (id)
);

-- ---------- Incidents, containment, recovery ----------
CREATE TABLE incidents (
    id               CHAR(36) PRIMARY KEY DEFAULT (UUID()),
    tenant_id        CHAR(36) NOT NULL,
    user_id          CHAR(36) NOT NULL,
    incident_type    VARCHAR(30) NOT NULL
                     CHECK (incident_type IN ('HIGH_RISK_LOGIN', 'STEP_UP_FAILED', 'TOKEN_REPLAY', 'MANUAL')),
    severity         VARCHAR(10) NOT NULL
                     CHECK (severity IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    status           VARCHAR(20) NOT NULL DEFAULT 'OPEN'
                     CHECK (status IN ('OPEN', 'CONTAINED', 'RECOVERING', 'RESOLVED', 'FALSE_POSITIVE')),
    risk_score       INT,
    summary          VARCHAR(500),
    opened_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    contained_at     TIMESTAMP NULL,
    resolved_at      TIMESTAMP NULL,
    resolved_by      CHAR(36),
    resolution_note  VARCHAR(500),
    CONSTRAINT fk_incidents_user FOREIGN KEY (tenant_id, user_id) REFERENCES users (tenant_id, id),
    CONSTRAINT fk_incidents_resolved_by FOREIGN KEY (resolved_by) REFERENCES users (id),
    CONSTRAINT uq_incidents_tenant_id_id UNIQUE (tenant_id, id)
);

CREATE TABLE containment_actions (
    id                 CHAR(36) PRIMARY KEY DEFAULT (UUID()),
    tenant_id          CHAR(36) NOT NULL,
    incident_id        CHAR(36) NOT NULL,
    user_id            CHAR(36) NOT NULL,
    action_type        VARCHAR(30) NOT NULL
                       CHECK (action_type IN ('LOCK_ACCOUNT', 'REVOKE_SESSIONS', 'FORCE_PASSWORD_RESET')),
    performed_by_type  VARCHAR(10) NOT NULL CHECK (performed_by_type IN ('SYSTEM', 'USER')),
    performed_by       CHAR(36),
    created_at         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reverted_at        TIMESTAMP NULL,
    CONSTRAINT fk_containment_incident FOREIGN KEY (tenant_id, incident_id) REFERENCES incidents (tenant_id, id),
    CONSTRAINT fk_containment_user FOREIGN KEY (tenant_id, user_id) REFERENCES users (tenant_id, id),
    CONSTRAINT fk_containment_performed_by FOREIGN KEY (performed_by) REFERENCES users (id)
);

CREATE TABLE recovery_requests (
    id               CHAR(36) PRIMARY KEY DEFAULT (UUID()),
    tenant_id        CHAR(36) NOT NULL,
    user_id          CHAR(36) NOT NULL,
    incident_id      CHAR(36),
    method           VARCHAR(20) NOT NULL CHECK (method IN ('EMAIL_OTP', 'ADMIN_APPROVED')),
    token_hash       VARCHAR(64) NOT NULL,
    status           VARCHAR(20) NOT NULL DEFAULT 'PENDING'
                     CHECK (status IN ('PENDING', 'VERIFIED', 'COMPLETED', 'EXPIRED', 'FAILED', 'CANCELLED')),
    failed_attempts  INT NOT NULL DEFAULT 0,
    approved_by      CHAR(36),
    expires_at       TIMESTAMP NOT NULL,
    created_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    verified_at      TIMESTAMP NULL,
    completed_at     TIMESTAMP NULL,
    CONSTRAINT fk_recovery_user FOREIGN KEY (tenant_id, user_id) REFERENCES users (tenant_id, id),
    CONSTRAINT fk_recovery_incident FOREIGN KEY (tenant_id, incident_id) REFERENCES incidents (tenant_id, id),
    CONSTRAINT fk_recovery_approved_by FOREIGN KEY (approved_by) REFERENCES users (id)
);

-- ---------- Audit and notifications ----------
CREATE TABLE audit_logs (
    id           BIGINT AUTO_INCREMENT PRIMARY KEY,
    tenant_id    CHAR(36),                                 -- NULL only for events before a tenant is known
    actor_type   VARCHAR(10) NOT NULL CHECK (actor_type IN ('USER', 'SYSTEM', 'ANONYMOUS')),
    actor_id     CHAR(36),
    action       VARCHAR(50) NOT NULL,                     -- e.g. ACCOUNT_CONTAINED
    target_type  VARCHAR(30),
    target_id    CHAR(36),
    incident_id  CHAR(36),
    ip_address   VARCHAR(45),
    details      JSON NOT NULL,                            -- never put passwords, tokens or OTPs here
    created_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_audit_logs_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id),
    CONSTRAINT fk_audit_logs_incident FOREIGN KEY (incident_id) REFERENCES incidents (id)
);

CREATE TABLE notifications (   -- simulated email outbox (dev only; bodies may contain OTPs)
    id          CHAR(36) PRIMARY KEY DEFAULT (UUID()),
    tenant_id   CHAR(36) NOT NULL,
    user_id     CHAR(36) NOT NULL,
    channel     VARCHAR(10) NOT NULL DEFAULT 'EMAIL' CHECK (channel IN ('EMAIL')),
    purpose     VARCHAR(30) NOT NULL,                      -- STEP_UP, RECOVERY, CONTAINMENT_NOTICE, ...
    subject     VARCHAR(200) NOT NULL,
    body        TEXT NOT NULL,
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_notifications_user FOREIGN KEY (tenant_id, user_id) REFERENCES users (tenant_id, id)
);

-- ---------- Indexes ----------
CREATE INDEX idx_login_events_user_time      ON login_events (user_id, created_at DESC);
CREATE INDEX idx_login_events_email_time     ON login_events (tenant_id, email_attempted, created_at DESC);
CREATE INDEX idx_sessions_user_status        ON sessions (user_id, status);
CREATE INDEX idx_refresh_tokens_session      ON refresh_tokens (session_id);
CREATE INDEX idx_risk_assessments_user_time  ON risk_assessments (user_id, created_at DESC);
CREATE INDEX idx_incidents_tenant_status     ON incidents (tenant_id, status);
CREATE INDEX idx_incidents_user              ON incidents (user_id);
CREATE INDEX idx_recovery_user_status        ON recovery_requests (user_id, status);
CREATE INDEX idx_audit_logs_tenant_time      ON audit_logs (tenant_id, created_at DESC);
CREATE INDEX idx_audit_logs_incident         ON audit_logs (incident_id);
